### ISSUE TITLE
system does not work with clojure 1.9.x

### ISSUE THREAD

**Issue by sveri** [danielsz/system#104]
Hi,

In your https://github.com/danielsz/system/blob/master/src/system/repl.clj you use 

    (require

instead of

    (:require

While this did work technically with clojure < 1.9 it is explicitly forbidden now with clojure 1.9.x

**Comment by sveri** [comment]
I just saw that @puredanger fixed that already but there is no release available with that fix. Will there be one any time soon?

**Comment by danielsz** [comment]
A new release is pending, yes. 

Are you aware that our snapshots are always up to date and safe to use?

**Comment by sveri** [comment]
I found them in the mean time and tried it with good results so far. Thank you very much :-)

**Comment by danielsz** [comment]
You're very welcome.
