### ISSUE TITLE
README: Problem in the usage instructions

### ISSUE THREAD

**Issue by plexus** [danielsz/system#107]
The README defines `prod-system` as:

``` clojure
(defn prod-system []
  "Assembles and returns components for an application in production"
  []
    (component/system-map
     :datomic-db (new-datomic-db (env :db-url))
     :mongo-db (new-mongo-db (env :mongo-url))
     :web (new-web-server (env :http-port) handler)
     :repl-server (new-repl-server (env :repl-port))))
```

There's at least one vector form too many there :) more problematic is this part:

``` clojure
(defn -main
  "Start the application"
  []
  (alter-var-root #'prod-system component/start)
```

which if I'm not mistaken assumes `prod-system` is a var containing a system-map, instead of a function that creates a system-map.

**Comment by danielsz** [comment]
Thank you, @plexus! 

I fixed it, but maybe it's time to do some more thorough housekeeping on the README. Maybe start moving stuff in the Wiki. The README is too long and too messy. Putting stuff in the Wiki would facilitate navigating the material, wouldn't it?
