### ISSUE TITLE
(go) or (reset) errors out with "Address already in use"

### ISSUE THREAD

**Issue by sooheon** [danielsz/system#109]
```
boot.user> (go)
    java.net.BindException: Address already in use
clojure.lang.ExceptionInfo: Error in component :web in system com.stuartsierra.component.SystemMap calling #'com.stuartsierra.component/start
```

I have tried with with the example boot project, both running `boot dev` in a terminal and calling it from within emacs CIDER.

**Comment by danielsz** [comment]
That's an error you would get if you already have a service listening on that port, whether intentional or not.

**Comment by sooheon** [comment]
Weird, I'm getting it completely stock on the boot examples project, could you just check once if you can reproduce it?

**Comment by sooheon** [comment]
It was because of the `:auto` option!
