### ISSUE TITLE
Handler components for other router libraries

### ISSUE THREAD

**Issue by cjhowe7** [danielsz/system#110]
Right now the handler component relies on `compojure`, but it'd be cool if it worked with `bidi` or other routers as well.

**Comment by danielsz** [comment]
It'd be cool. Agreed. Were you thinking of trying your hand at it?

**Comment by cjhowe7** [comment]
Yep, I'll have a PR soon.

**Comment by dupuchba** [comment]
Hello friends, any news on this one ? I am facing the same issue

**Comment by danielsz** [comment]
Feature complete and deployed in latest snapshot. Thanks you, Baptiste!
