### ISSUE TITLE
go task not found in boot example project

### ISSUE THREAD

**Issue by shakdwipeea** [danielsz/system#113]
In the boot example project

> You’re all set now. You can connect to your REPL from your favorite editor, and then start your application: In the boot.user namespace, type:

> `boot.user=>  (go)`

I get this error
```
 (go)
             java.lang.RuntimeException: Unable to resolve symbol: go in this context
clojure.lang.Compiler$CompilerException: java.lang.RuntimeException: Unable to resolve symbol: go in this context, compiling:(*cider-repl example-boot*:63:12)
```

I apologize for the blank issue created.

**Comment by danielsz** [comment]
Thank you for bringing this up. 

The `build.boot` was missing the appropriate `require`. 

```clojure
(require '[system.repl :refer [go reset]])
```

I also changed the wording of the `README` to emphasize the fact that you don't have to restart manually. Auto-managed restarts and reloads are after all what `system` is about.

Please let me know if this helps.

**Comment by shakdwipeea** [comment]
Works perfectly, Thanks.
