### ISSUE TITLE
First reload unnecessarily restarts system

### ISSUE THREAD

**Issue by zalky** [danielsz/system#119]
I'm seeing some puzzling behaviour in my development build, using system. Basically, the first time I save a cljs file, system stops, reloads _all_ my clj files, and then restarts system components. On subsequent cljs edits, things work as expected: no system restart, and only cljs is recompiled.

I'm not sure if I'm doing something wrong. In all other ways, system seems to be behaving as expected.

Here's my build pipeline:

```clj
(deftask dev
  "Run development system."
  [r nrepl-port VALUE int "nREPL port"]
  (load-env! dev-env)
  (comp (watch)
        (system :sys #'core/dev-system
                :mode :lisp
                :auto true
                :files ["comms.clj"])
        (reload)
        (sass)
        (cljs-repl :nrepl-opts {:port nrepl-port})
        (cljs :source-map true
              :optimizations :none
              :compiler-options compiler-options-dev)
        (sift)
        (target)))
```

and here's `core/dev-system`

```clj
(defn dev-system
  "Assembles components for dev application."
  []
  (-> (component/system-map
       :datomic        (db/datomic-db datomic-config)
       :sente          (socks/new-channel-sockets
                        comms/sente-handler
                        (adapter/get-sch-adapter)
                        {:wrap-component? true})
       :app-middleware (ware/new-middleware
                        {:middleware [ring-format/wrap-restful-format]})
       :middleware     (ware/new-middleware
                        {:middleware [[ring-defaults/wrap-defaults
                                       site-defaults]
                                      ring-gzip/wrap-gzip]})
       :sente-endpoint (endpoint/new-endpoint socks/sente-routes)
       :app-endpoints  (endpoint/new-endpoint comms/static-routes)
       :handler        (handler/new-handler)
       :http           (server/new-web-server 4000))
      (component/system-using
       {:sente          [:datomic]
        :sente-endpoint [:sente]
        :app-endpoints  [:app-middleware :sente-endpoint]
        :handler        [:sente-endpoint :app-endpoints :middleware]
        :http           [:handler]})))
```

**Comment by danielsz** [comment]
Yes, this is what I see as well. The machinery behind the reloading is involved and does the best it can with the tools it leverages (Boot and tools.namespace). It is quite possible that there is a way to streamline it further and get rid of the first redundant reload. If this is important enough to you, I would encourage you to delve in the code and submit a PR.

**Comment by zalky** [comment]
Thanks @danielsz , it's good to know this is at least known behaviour, I was worried that I was doing something wrong. If the rebooting poses a problem, I'll have a look.

**Comment by danielsz** [comment]
Awesome. Closing for now. Please feel free to reopen if you decide to tackle this.
