### ISSUE TITLE
new http-kit function has validation problem

### ISSUE THREAD

**Issue by bamarco** [danielsz/system#120]
`system.components.http-kit` injects `:join? false` into the options map in the `new-http-kit` function, but the `Options` schema validator contains no `:join?` key causing an error. The `jetty` component by contrast does include the `:join?` key in the validator.

**Comment by danielsz** [comment]
Good catch. Would you like to submit a PR? Thanks.

**Comment by danielsz** [comment]
Fix available in latest snapshot release.
