### ISSUE TITLE
Reload time (question)

### ISSUE THREAD

**Issue by Atsman** [danielsz/system#124]
Hello, i am using multiple components from this repo, like aleph and hicary cp.

How much time it should take to reload system. Because now it seems to high, not really comfortable to work with. When i call system.repl/reset, hicary pool restart and aleph is too slow.

Should i configure it in some special way?

**Comment by danielsz** [comment]
No special configuration is needed. My systems always reload in under a second. I don't use aleph or hicary, so you'll have to debug the problem yourself and post your findings. Thank you.

**Comment by Atsman** [comment]
@danielsz ok will try to fix it. By the way i am still have 30-60 seconds reload time. :(

**Comment by Atsman** [comment]
@danielsz the problem was in my own code, on db start i have some migration/schema initialization staff. I fixed that. Sorry for bothering.

**Comment by danielsz** [comment]
No problem. Happy you traced it back to the source of the problem. Thanks for the update.
