### ISSUE TITLE
Question: Where did the mount branch get to?

### ISSUE THREAD

**Issue by markjfisher** [danielsz/system#128]
Hi, I'm just kickstarting my clojure development again, and came across system as I've decided to use boot this time over lein and one way or the other I was lead here.

Previously I used mount, and liked how it worked, so I was looking to see if system and mount were in some way compatible, and if it's a "thing". Came across the closed issue, and branch, but it seems to have halted (2 commits in, 129 behind at this time).

Is there anything more to get that going, or is it not worth it and maybe I should experiment with using just system?

**Comment by danielsz** [comment]
Hi Mark, depends how important `mount` is to you and how courageous you are. But it will be lonely out there. `system` is the easy, pragmatic answer and you will not lose out on anything. It's two ways to do the same thing.
