### ISSUE TITLE
Incompatible with new nrepl

### ISSUE THREAD

**Issue by plexus** [danielsz/system#131]
nrepl has moved to a new organization, and so the namespaces have also changed.

In particular `clojure.tools.nrepl.server` is now simply `nrepl.server` ([src](https://github.com/nrepl/nrepl/blob/master/src/clojure/nrepl/server.clj))

This leads to

```
Caused by: java.io.FileNotFoundException: Could not locate clojure/tools/nrepl/server__init.class, clojure/tools/nrepl/server.clj or clojure/tools/nrepl/server.cljc on classpath.
```

Some kind of detection/fallback would be useful here.

**Comment by plexus** [comment]
Nevermind, seems this is actually addressed, but only available as a SNAPSHOT version so far.

**Comment by danielsz** [comment]
Thanks. I've cut the 0.4.2 release.

**Comment by plexus** [comment]
Thank you! :100:
