### ISSUE TITLE
First name and Last name  accepting spaces

### ISSUE THREAD

**Issue by akashtippa** [danielsz/system#133]
Location: ALL request access form
OS / OS Version: Windows 10
Device / Browser: Chrome  80.0.3987.87
Env: production

Expected Results: First name and Last name field should not accept the spaces in request access forms.
Actual Results: First name and Last name field accepting the spaces in request access forms.

Steps to Reproduce;
1: Launch SYSTM app on chrome browser using url  https://www.systm.app/landing
2: select Intelligent booking access
3: select any type of request access form
4: enter spaces in First name and Last name
5: enter email id and website link tap on request access
6: request sent to admin

**Comment by danielsz** [comment]
Wrong repository. This is system, a Clojure community repository, not the booking system.
