### ISSUE TITLE
Trouble Sente

### ISSUE THREAD

**Issue by brandonparsons** [danielsz/system#17]
I'm getting the following error when trying to use Sente:

`AssertionError Condition failed in `taoensso.sente:?` [pred-form, val]: [((fn* [p1__13000#] (satisfies? interfaces/IAsyncNetworkChannelAdapter p1__13000#)) web-server-adapter), {}]  taoensso.encore/assertion-error (encore.clj:310)`

I have followed the instructions in #14.

Any thoughts/tips?

**Comment by brandonparsons** [comment]
I was using a new version of Sente, which requires some changes from what you have here.

**Comment by danielsz** [comment]
@brandonparsons I don't know exactly how, but I failed noticing your ticket. Are you OK now?

**Comment by brandonparsons** [comment]
Hello! Yep, all good now. I stole your code and added the new lines that the new version of sente requires.

**Comment by danielsz** [comment]
I'm happy everything is good. FYI, system 0.1.6 brings support for the new Sente signature (support for web servers besides http-kit).
