### ISSUE TITLE
Starting a system automatically

### ISSUE THREAD

**Issue by mhuebert** [danielsz/system#18]
I'm writing a server based on the `boot` example, trying to learn boot and component.js simultaneously. Given the boot task:

```clj
(deftask dev
  "Run a restartable system in the Repl"
  []
  (comp
   (environ :env {:http-port 3000})
   (watch :verbose true)
   (system :sys #'dev-system)
   (repl :server true)))
```
And the system:

```clj
(defn dev-system []
  (component/system-map
   :web (new-web-server (Integer. (env :http-port)) handler)))
```

Where might I tell the system to start automatically, so that I don't have to open a repl first and run (go) to run the server?

**Comment by danielsz** [comment]
Hi!

This is a good question with several avenues of tackling it. The first thing to note is that starting the system at startup is typically what you'd want to happen in production. The example project shows how you start a system in the [main](https://github.com/danielsz/system/blob/master/examples/boot/src/example/core.clj) entry point. This is working because when preparing an uberjar, you specify the main class in the configuration (boot task). For example: 

```clojure
(deftask build
  "Builds an uberjar of this project that can be run with java -jar"
  []
  (comp
   (aot :namespace '#{my-app.core})
   (pom :project 'my-app
        :version "1.0.0")
   (uber)
   (jar :main 'my-app.core)))
```

Now you can run your program with `java -jar`, etc. However, if you want to start the *development* system and *not* open a REPL, you can do that by leveraging Boot's support for command-line scripting. 
The process is described on the wiki: https://github.com/boot-clj/boot/wiki/Scripts
You can even write a `-main` method in `build.boot` itself, prepend the appropriate shebang, chmod it and run that.

```clojure
(deftask run
  "Run a system in the command line"
  []
  (comp
   (environ :env {:http-port 3000})
   (system :sys #'dev-system)))

(defn -main [& args]
  (run))
```

I hope this helps. Please let me know if this works for you.

**Comment by danielsz** [comment]
@mhuebert

**Comment by mhuebert** [comment]
hey, thanks!

When I put that in my boot file and run it, I get:

```
clojure.lang.ExceptionInfo: Unable to resolve symbol: run in this context
    data: {:file
           "/var/folders/gk/bxgzz2tn5gs2249f05hkw2jh0000gn/T/boot.user6463214541931681839.clj",
           :line 13}
```
I assume this is from the line
```
 (run :main-namespace "example.core" :arguments [#'dev-system])
```
...Does `run` come from another namespace that I haven't required?

**Comment by danielsz** [comment]
`run` is a built-in task in recent Boot, so it's likely because you're not running the latest Boot. You can verify your version with:

```sh
$ boot -V
```

And you can upgrade with: 

```sh
$ boot -u
```

**Comment by danielsz** [comment]
Please scrap that. `run` is not yet a built-in task. You'll need this:

```clojure
(deftask run
  "Run the -main function in some namespace with arguments."
  [m main-namespace NAMESPACE str   "The namespace containing a -main function to invoke."
   a arguments      EXPR      [edn] "An optional argument sequence to apply to the -main function."]
  (with-pre-wrap fs
    (require (symbol main-namespace) :reload)
    (if-let [f (resolve (symbol main-namespace "-main"))]
      (apply f arguments)
      (throw (ex-info "No -main method found" {:main-namespace main-namespace})))
    fs)) 
```

**Comment by danielsz** [comment]
With the latest `system 0.1.7`, you don't need to include above task, as it ships with it. 

This should suffice:

```sh
$ boot dev-run
```
 
I would appreciate it if you could try it out and let me know of any other problems. Thanks!

**Comment by mhuebert** [comment]
Hey, that worked! Thanks for all your help.

I've realized though that what I am really wanting may be different from what this is set up to do. Even if I reset the system from the REPL, the server continues to run the original code, so I have to stop the process and re-run `boot ...` whenever I've made changes that I want to reflected in a browser. Is this expected behavior, or have I got something wrong? It seems odd that I can (stop) and (reset) the system from the REPL but this doesn't actually load changes I've made.

What I'm aiming for:
- Start a server that I can view in a browser
- Start a repl that I connect to in emacs
- Start the "system"
- Load updated code either when files change (watch) or with a command from the repl

**Comment by danielsz** [comment]
What you describe is exactly what the `dev` task does (not `dev-run`). 

Maybe you can follow this step-by-step [tutorial](https://github.com/danielsz/holygrail) and see if this clears it up for you.

**Comment by mhuebert** [comment]
Ah I see what's going on. I'm using [rook](
https://github.com/AvisoNovate/rook) and creating a handler in app.server.
It relies on code in app.resources.projects. When I update the projects
file, that file does reload, but since app.server was not modified, the
handler is not refreshed and I don't see the changes.

On Mon, Apr 27, 2015 at 6:43 PM, Daniel Szmulewicz <notifications@github.com

**Comment by mhuebert** [comment]
Got it working now... previously, I had something like:
```
(def handler 
  (rook/namespace-handler
    ["projects", 'server.resources.projects]))
```
I made it a function:
```
(def make-handler []
  ...)
```
And then of course call `(make-handler)` when I define the system:
```
(component/system-map
   :web (new-web-server (Integer. (env :http-port)) (make-handler))
```
The last thing on my wish list would be for the repl to run (reset) automatically when I save a file..

**Comment by danielsz** [comment]
Great to hear things are working now. Regarding the REPL resetting every time you save a file, I'll think about it. Not a big fan myself, but maybe as an option switch. Stay tuned.

**Comment by mhuebert** [comment]
Alright. I appreciate your help and patience with all this.

I don't think I would want the REPL to reset on file changes, but I would
often want a web server doing so.
If I understood boot better I could probably be of more help. Maybe it
would make sense to set up a separate task that only runs an auto-reloading
web server. I tried adding (watch) to dev-run but that doesn't seem to do
anything even though it does notice when files change. Is it possible to
have it trigger (reset) on the system?

**Comment by danielsz** [comment]
`system 0.1.8-SNAPSHOT` adds hot-reload functionality, i.e. when you save your file, the system is restarted. Have a look in the [build.boot](https://github.com/danielsz/system/blob/d5c9161ec75617f255afd824af2a4879c80992de/examples/boot/build.boot) file for an example. 

Please type `boot dev` in the command line, connect to the REPL and start your system once with `(go)`, subsequent file save changes will trigger a system restart. I would love to know how this works for you.

**Comment by mhuebert** [comment]
This is great, just what I was hoping for :-). Thank you!

**Comment by danielsz** [comment]
You're welcome. I'm adding file-based granularity to the hot-reloading functionality, so you don't need to restart the system with absolutely every change. Instead, you provide a vector of file names as an option, and only if those files change, the system will restart.

**Comment by danielsz** [comment]
Added in 0.1.8-SNAPSHOT. Help with testing the new functionality would be awesome. Again, usage example is in `build.boot`.

**Comment by mhuebert** [comment]
That's great. I was using the REPL-auto-reloading all afternoon and found
it useful. I'll try the new feature tomorrow.
