### ISSUE TITLE
Some considerations ...

### ISSUE THREAD

**Issue by robjens** [danielsz/system#19]
Hi, I've been running into a few issues which might warrant some additional input from other folks who've been occupying themselves with system/components.

The problem I think is best described as `dependency hell`. Although system in this case is a great idea, there is the problem of the way components are referenced currently. That is, being defined in a `project.clj` key/value pair either `:dependencies` or under `:plugins` depending on use (here mostly dependencies). 

The case involves the componentization of `clj-webdriver`. At first thought, it seems suitable for such endeavor: it has a clear `start` (set-driver! ...) and `stop` (quit) point, it has state and it requires flexible user input which may change depending on use/time/configuration (e.g. a bundle of test actions predefined to run). Furthermore it seems logical that it depends on some (currently used) components, most notably, a web server (with routes, assets hosted and other things) to be present before it should attempt to do its magic.

The problem comes from the fact that each and every single package conflicts with selenium dependencies. Its a real nightmare of exclusions. This alone would make it a hard sell to componentize in this current suite.

But the problem is not so much limited to this specific case I feel. It seems to me, a logical part of 'breaking things up in reusable pieces' involves a little less 'tweaking dependencies to be just right'.
Ideally, one would imagine a separate running virtual machine in a virtual machine, without inheriting all of the parent project tree. Pulling in dependencies isn't that hard (I use Alembic) and experiment currently a bit with a second protocol applied on top of `Lifecycle` (named Prerequisite) to feed it `(instill [dependencies] ...)` before start and stop get to run on the component.

One consequence though, is that - should one to have a pristine environment/dependency tree - any referenced symbols from other components, or basically just any dependency at all, need to be provided explicitly. For example, currently the `server` component in system uses the non-componentized routes and (middleware/default) wrappers from Compojure and any component can basically use them although, as usual, one would have the include them in the component namespace required symbol list of course.

Anyway I'd be interested in some thoughts, am I overthinking this, not/indeed a problem, is the 'dream' of more isolation feasible, and if so, how might one approach it?

Thanks :)

**Comment by robjens** [comment]
Hmmm to somewhat answer my own question, a project like [this](https://github.com/projectodd/shimdandy) would be able to pull off a 'pristine work tree', but then again lein also has something like profiles which allows for different clojure versions (for example) to be defined... only not for them to run next to eachother really I guess although one can simply still launch separate processes, one for profile :alpha and one for :bravo, I don't think interop is that easy anymore though :P We're talking inter-process coordination here. That just never is easy.

**Comment by danielsz** [comment]
Hi Rob, it looks like you'll like the pods functionality that boot-clj
provides, based on the shimdandy library you referenced earlier.

**Comment by robjens** [comment]
@danielsz Thanks. I can appreciate it when someone can translate my mumbo-jumbo to concrete solutions/projects ^^

Cheers,

Rob
