### ISSUE TITLE
Name is difficult to google

### ISSUE THREAD

**Issue by danielsz** [danielsz/system#2]
Please feel free to suggest alternate names.

**Comment by robjens** [comment]
@danielsz `danielsz system github` would work, even considering the lousy state that search algorithm is in, should yield results

Btw, I like `assiduous`... referring to the persevering, continuous effort ridding oneself (erh, project) of all state. Antonym of dispersed (read: Vars all over the place).

**Comment by ExMateria** [comment]
Sister Tam (Don't know if anyone is a Firefly fan here)

**Comment by ExMateria** [comment]
Sis Tam for short

https://www.youtube.com/watch?v=MoMpau_B2Io

**Comment by metasoarous** [comment]
Maybe something to emphasize that it's a collection of ready made components. A "toolbox" immediately comes to mind. Maybe something like `comp-box` or `component-box`.

I realize this thread is a bit old... but it's still open so there's my two sense :-)

**Comment by danielsz** [comment]
Thank you, @metasoarous. 

I am going to close this, as time has passed, and the name has gotten somewhat known, and it is in line with the naming of `components` on which it builds. 

Not perfect, sure. But then again what is?

I wish to thank everybody who suggested something. It is much appreciated.
