### ISSUE TITLE
How to handle handler?

### ISSUE THREAD

**Issue by stig** [danielsz/system#29]
I am a Ring/Compojure beginner and trying to use this library. In README you have this:

    (defn dev-system []
      (component/system-map
       :datomic-db (new-datomic-db (env :db-url))
       :mongo-db (new-mongo-db)
       :web (new-web-server (env :http-port) handler)))

This is slightly confusing to me. Do you not need to create the handler as a
separate component? I don't see how the db(s) are injected into the handler in
the above example. (I *assume* the handler is what needs the dbs.)

**Comment by danielsz** [comment]
Hi, 

I only componentize external dependencies. When the handler needs to access the db, it  does so via the `system` map.
Does that makes sense?

**Comment by stig** [comment]
Yes, I think so. It was't obvious to me though.

**Comment by danielsz** [comment]
I probably need to introduce a full CRUD example. At #24 we've discussed along similar lines.

**Comment by stig** [comment]
> I probably need to introduce a full CRUD example. At #24 <https://github.com/danielsz/system/issues/24> we've discussed along similar lines.
> 
*nod* that is indeed similar to my issue, except I didn’t even realise I could poke into the system map and thought it was a broken example. :-)

Stig

**Comment by danielsz** [comment]
An advanced example has been published. Can we close this?

**Comment by stig** [comment]
Sure.

**Comment by danielsz** [comment]
:+1:
