### ISSUE TITLE
System with dependencies + boot system task example?

### ISSUE THREAD

**Issue by rej156** [danielsz/system#31]
I'm not entirely sure how a production system could be started,
I want the new-web-server component to start after a datomic-db component.

In this case,
(def conn (:conn (:datomic-db system))
would initialise as nil!

**Comment by danielsz** [comment]
Please refer to the newly posted example that demonstrates this. 

https://github.com/danielsz/system/tree/master/examples

Please let me know if this makes it clear for you.

**Comment by danielsz** [comment]
Closing issue for now. 
There is a dependency injection example in the examples folder.  
If you have any question, feel free to reopen.
