### ISSUE TITLE
Integrating with a clojure.test suite?

### ISSUE THREAD

**Issue by mathias** [danielsz/system#35]
Hello,

I'm having some trouble running the ring web app and Postgres components as part of a clojure.test suite . In particular, when I try to output the following in a function that's called as part of database setup code, run from the test suite, I get nils:
```clojure
  (println "env db: " (env :database-url))
  (println "system: " (:db-spec (:db system)))
```

This is making me think that the `system` components are reloading (works in dev, is able to connect to the database in dev, but the test suite isn't getting access to the environ or system components that were set up. I'm not quite sure how to get around this -- if my code doesn't know about `system` then it's hard to tie the database to the web app (and indeed, I can't even get the environ ENV vars that I'm setting to appear, as seen above.) Maybe I'm just missing something conceptually here, but it seems like this just isn't working for running with clojure.test tests?

Here's my testing task in my `build.boot` file:
```clojure
(deftask autotest
  "Run server tests"
  []
  (set-env! :source-paths #{"test" "src"})
  (comp
   (environ :env {:http-port "3000"
                  :database-url "postgres://localhost:5432/foo_test"})
   (watch :verbose true)
   (system :sys #'dev-system
           :hot-reload true
           :auto-start true
           :files ["handler.clj"])
   (test)))
```

Any help appreciated. Thanks!

**Comment by danielsz** [comment]
Hello Matthias, 

Thank you for opening this issue. 
I'm not really surprised about your findings, since the tests run in a pod, that is to say in isolation.  t
Solving this will require thinking about the problem, and coming up with a strategy. 

Instead of exposing the system map to your test suite, why not start the system inside your test? Do you think you can try this approach?

**Comment by mathias** [comment]
That's a good idea. I'll give it a try.

Thanks!

**Comment by danielsz** [comment]
Awesome. 

If you come up with a satisfying solution, please do not hesitate to share your insights here (or in the README).

**Comment by danielsz** [comment]
Closing in the meantime. Feel free to reopen if I missed something.
