### ISSUE TITLE
jetty server config is limited

### ISSUE THREAD

**Issue by SevereOverfl0w** [danielsz/system#41]
The run-jetty command takes a significant number of arguments in it's config, is there any way to support them all? https://ring-clojure.github.io/ring/ring.adapter.jetty.html

**Comment by danielsz** [comment]
Yes, of course. PR welcome.

Would you like to give it a try? You can take a look at the http-kit and Immutant components to see how it's done. Both support all of their configuration switches.

**Comment by danielsz** [comment]
All options are supported as of `0.2.0-SNAPSHOT`

**Comment by SevereOverfl0w** [comment]
Excellent. Sorry I never got back to you. Very busy.
