### ISSUE TITLE
Hot reloading with Leiningen?

### ISSUE THREAD

**Issue by jonathanj** [danielsz/system#42]
I see there is support for hot reloading with Boot but apparently none for lein. Is this an intentional decision? Would you consider adding support for it?

**Comment by danielsz** [comment]
Thank you for bringing this up. 
I've updated the [README](https://github.com/danielsz/system#leiningen) to address this question. 
In a nutshell, we recommend @bhauman's excellent Figwheel library.

**Comment by jonathanj** [comment]
Figwheel is an excellent piece of software. However I was under the impression that Figwheel was for hot reloading ClojureScript, whereas my interest is reloading my ring (and associated) Clojure code. Perhaps `lein-ring` and `ring-server` are appropriate choices but it's not clear how they  should interact with system.

Sorry about not being clear about this originally.

**Comment by danielsz** [comment]
No problem.

Leiningen runs in a separate JVM instance as your application, that is why it is not a good candidate for  reloading goodness. 

What you always can do is restarting the system in the REPL manually, ie `reloaded.repl/reset`.

**Comment by jonathanj** [comment]
Thanks for taking the time to respond. Having invested the time to get Boot up and running and after some initial pain it seems to all be working quite well, which makes me happy!
