### ISSUE TITLE
Once-off system initialisation function?

### ISSUE THREAD

**Issue by jonathanj** [danielsz/system#43]
I have some code (a ring app served with jetty) that stores state in an atom for the duration of the application, the data is not persisted anywhere. Unfortunately every time a route handler is changed the application is reloaded and my atom is trashed. I guess this can probably be worked around with a `defonce` for the state but that feels like a kludge.

I couldn't find anything about something like this, did I miss it or would you suggest something else?

**Comment by danielsz** [comment]
Yes, when your application restarts, your state gets trashed. But this is the behavior we want. `defonce` won't help here, as the `refresh` function in `tools.namespace` takes care of deleting all vars. 

What can you do?  A couple of ideas: 
* If possible, recreate the state when the application starts.
* Finetune the hot-reloading facility. Remember that when you specify files with the -f option, only those filenames will trigger a restart. 
* Don't restart automatically, restart manually in the REPL (`reloaded.repl/reset`)
* Revisit the design of your app. Don't let non-persisted state floating around. The back-ends rarely needs that. What is your use case?

**Comment by jonathanj** [comment]
1. The state isn't persisted so recreating it isn't a realistic possibility, there is no requirement for persistence so building that functionality only for testing purposes seems like quite a detour.
2. This is a potential solution, although a little clunky.
3. I'm not entirely sure how restarting manually helps my situation. If nothing is reloaded automatically then I lose the benefits of hot-reloading Clojure code, when I restart manually then my state is reset the same way automatically restarting would?
4. The state is intended to be very short lived (under 5 minutes) session information (it's basically a bunch of bytes and some Manifold `Deferred`s) and reside only in memory. In production circumstances the client would simply retry when something goes awry, in a test environment I need to be able to iterate without having to rebuild my state manually every time I change any code.

**Comment by jonathanj** [comment]
In my case, the state is an atom map of session information. Each session is a small piece of isolated state and a new one can trivially be created by calling the API. The overall operation of the application depends only on what the session being acted on contains.

I think what I want is some way for the system being restarted to be involved in creating state for the new application, at least that way I can choose which state is not conducive to reloadable systems and which state is benign.

**Comment by danielsz** [comment]
Session information gets deleted when you restart a Ring server. It's just how things work. Nothing survives a restart. You start afresh. And that's the purpose of restarting a system.

**Comment by nowprovision** [comment]
Restarting is overkill. You can eval into a repl fns without restarting the system, why do you need to restart to see changes? How are your route handlers setup? You'll only see this problem if you have too much directly in the fn handler passed to jetty (you can also pass the var itself since it implement ifn but maybe not best idea with component), if it delegates out you can eval those functions into the nrepl server without (restart). Sometimes one can go a whole day without (restart)
