### ISSUE TITLE
Check if a component is started before execute the code to stop it

### ISSUE THREAD

**Issue by jordillonch** [danielsz/system#44]
I think it is a good idea to check if you started a component before to execute the code to stop it.
The point is when you are developing and trying your code you can introduce some bug that avoid the start of a component and after you fix it you are unable to restart the system because you can not stop the component that have the bug.

**Comment by jordillonch** [comment]
I'm sorry. I saw the rabbitmq component without this check but I also saw other components with this check :)

**Comment by danielsz** [comment]
No problem, if you identify a particular component where more checks are desirable, I would most certainly accept a PR.
