### ISSUE TITLE
Provide a working example (README)?

### ISSUE THREAD

**Issue by robjens** [danielsz/system#47]
Personally, I get the implied message from the opening line, that this example would be a 'follow along and do as I do' (starts with, "First, we'll...."). I came to me, that the nature of `system` makes it hard to give a working example out of the box (Stuff Just Works (TM)). Should we perhaps add a minor introduction about the required additional dependencies (and/or plugins) and the internal namespace (which exposes `handler`)? Or perhaps, due to that composable nature, just refer to the example projects (boot/lein) since those actually do contain the required (albeit perhaps slightly outdated at times, as a worse case) dependencies/plugins.

I guess what further adds to some confusion, is the later mentioning of `ns front-end.webapp.handler` in a somewhat different context.

Maybe it's just me, but I'm never that fond of the (go find out yourself) attitude which has hidden (phony) code references in examples (especially not on the README) that so hallmark the JS community (grab reference libraries from code, show only non-working, most trivial examples, mention but not elaborate on  obscure edge-case or common use-case scenario's). Which doesn't mean I think `system` has that btw, I am actually wondering if there would be much to write about in the sense that it needs a manual. Most is up to the users creativity I guess, but a nice tutorial showing _all_ steps might be a nice/useful addition.

Your thoughts?

**Comment by danielsz** [comment]
Thank you, @robjens, I am totally with you regarding those comments. 

I would be extremely happy to pull in edits that add clarity and accuracy. Likewise, 
I would be happy to pull in edits that remove triviality or confusion.  

Nobody is more suited to submit a PR than the user who discovers obscure or incomplete information while trying to make sense of a library.

**Comment by robjens** [comment]
The only suitable answer :) I'll do that
