### ISSUE TITLE
Make validation on by default but optional under client control

### ISSUE THREAD

**Issue by brabster** [danielsz/system#56]
We could refactor the validation slightly to allow client control of whether validation takes place, using s/with-fn-validation instead of calling s/validate ourselves

https://github.com/plumatic/schema#schemas-in-practice

That might help if we make a mistake and over-constrain validation somewhere - client could just not validate until the issue is resolved. I might add this feature and update docs before adding new validation to previously unconstrained options

**Comment by danielsz** [comment]
Good idea. An external resource like Jetty can indeed have different options when a new version gets released, thus becoming unusable with our validations.
Although one could argue that this is also the point of validations, to make our expectations explicit. 

If the implementation of the feature you're proposing is simple and elegant, I'll take it.

**Comment by brabster** [comment]
OK cool, I'll play for validation on by default but client can choose to turn off if they want to - seems like the best compromise, safe by default but you can take the guard rails off if you know what you're doing.

I'll have a crack at it and PR you. There's also a neat type hint-style functionality that might make sense to switch to here, so I'll point that out if I use it.

Thanks for the patience and for shouting up for help in the first place - very useful for me!

**Comment by danielsz** [comment]
Thank you, @brabster. You're doing great work.

**Comment by brabster** [comment]
Hmm, had a good look into this and I'm not sure how to do it. Problem seems to be that validation is either global or hardcoded, i.e.
 - (s/set-fn-validation! true|false) would affect any validation going on in the app, not just system
 - (s/with-fn-validation ...) actually toggles the global above and can't override the following
 - (s/validate ...) cannot be override by a caller
 - ^:always-validate (and ^:never-validate) cannot be overridden by a caller

Maybe the best plan is to not worry about it until someone actually raises an issue!

**Comment by danielsz** [comment]
That is always the best approach! :-)
Thanks for your pull requests. I'll be looking into them as soon as I have some time (this week).

**Comment by danielsz** [comment]
The idea is valid, but might be overkill as nobody has requested that feature. 
Closing for now.
