### ISSUE TITLE
API to check the status of the components

### ISSUE THREAD

**Issue by giorgio-v** [danielsz/system#64]
I think it would be useful to have some way to report about the status of the components. This could then plugged into a monitoring infrastructure of some sort.

This feature (provided we agree on consider this request in this way! :) ) could alternatively be added to Sierra’s component library. Seems more appropriate here, though.

HTH

**Comment by danielsz** [comment]
That could be useful, but why not in a separate library altogether?

**Comment by giorgio-v** [comment]
Because it seems to me there is no consistent way to infer the status of the different component just by looking at the overall map. Or maybe I’m missing something?

**Comment by danielsz** [comment]
Well, you can monitor your infrastructure like people have always done, using Riemann to mention just one tool.

Why would you want to integrate a monitoring API in the components themselves? How unwieldy is a component going to look if it needs to support monitoring on top of lifecycle management?

You have shared an idea without explaining how you envision the implementation. So it's difficult for others to evaluate it at this point. But I would encourage you to continue this conversation with more explanations and maybe a concrete example of the API you're imagining.

**Comment by giorgio-v** [comment]
Good points. I'll try to clarify:
- what I'm proposing is not full blown monitoring interface. As you said, that would be unwieldy. 
- what I'm proposing is a way to answer, in consistent manner, the question ”is this component up or down?“ Maybe this would still be to cumbersome, that's true. 

The use case that drove me to open this issue is the following. I deploy a test prototype, which exposes an http endpoint that I use in combination with Ansible to check whether the app is up and with the expected version etc etc. So far, so good: Ansible waits for the app to bounce and reports back the version check. When I connect with my browser I see that Sente’s channel is correctly opened but I don't see any data, so I take a look at the logs and I discover that Datomic crashed due to memory issues (no problem, my fault). 

With the proposed change it would be possible to check the status of the components as soon as the app starts up, while we are still deploying it and so we can fail fast or skip some other subsequent steps. 

Hope this helps. 



--
Giorgio Valoti

**Comment by danielsz** [comment]
OK, thanks for the clarification. 

I suppose it will all come down to the implementation. 

Why don't you show us how you plan to do that for one or two components, and then we'll take the conversation further.

**Comment by giorgio-v** [comment]
Sure. I’ll try to come up with a proposal tomorrow, time permitting. But yes, I’ll get back to you with something more concrete.
