### ISSUE TITLE
Support for mount and other runtime state management libraries 

### ISSUE THREAD

**Issue by danielsz** [danielsz/system#73]
Support for mount and mount-lite

The grand vision is that all the components should have their mount counterparts.

https://github.com/tolitius/mount

https://github.com/aroemers/mount-lite

**Comment by aroemers** [comment]
Hi @danielsz,

Something like [this](https://github.com/aroemers/system/commit/814897b49d1df90a63d991b805aa21b45423534f)? It supports both mount and mount-lite (and no mount at all). It is a WIP.

**Comment by danielsz** [comment]
Hi @aroemers, 

Exactly. That looks great. So awesome!

I was actually envisioning them to live in their own namespace, a sibling of `system.component`. I don't have a good name yet, but feel free to suggest one.   

Down the road, we can share the validations too. Not urgent. 

PS: Thanks for `mount-lite`!

**Comment by danielsz** [comment]
What do you think of `system.state` as the top-level namespace for mount components?
That would be, for example, `system.state.jetty`, `system.state.jdbc`, etc...
Good idea? Bad idea?

**Comment by tolitius** [comment]
yea, I agree: it is best for mount and component "components" to be decoupled.

as far as the name `system.component` of course sounds more of what it is: i.e. `system.component.jetty` sounds a bit better than `system.state.jetty`. another option I can think of is `system.mount.jetty` which both:

* implies that "you need to mount jetty (thing) to your system", and
* structures system's code a bit better:

```system
├── mount
└── component```

**Comment by danielsz** [comment]
tHi Anatoly, 

Yes, I don't know if was clear enough, but I had that same structure in mind. 

``` bash
system
├── state
└── component
```

If you prefer `system.mount`, that is fine by me. I initially thought of `state` because I had the impression it was used a lot in the docs, but I haven't sufficiently used `mount` or `mount-lite` to have a good feel for it, so if you and @aroemers agree on `system.mount`, that's what it is going to be. 

I will merge @aroemers 's work as soon as he can submit a PR. It doesn't need to be perfect, it doesn't need to do everything, the priority I think is to have the foundation so that everybody can build upon.

Thank you!

**Comment by tolitius** [comment]
Hi Daniel,

  Sure, it was clear, and you're right I use the term `state` in docs. The slight semantic difference here is `system` vs. `application`.

  To me (and I am not a native English speaker), an `application state` is clear, whereas a `system state` is missing the context of a `system`: i.e. does my application have many systems, is this system outside of my application, is my application inside this system, etc..

  From that line of thinking (and it could be just me), I thought `system.mount.jetty` is a bit clearer.

  But don't take my word for it. You know a lot better (than me) how people use `danielsz/system`, and what would make a better name.

Thanks for being open to both worlds! :)

**Comment by danielsz** [comment]
I agree with you. I also honestly think that `system.mount` will be less confusing, and it is consistent with taking the name of the library it implements, like with the name `component`. 

If @aroemers is good with it, we're all set. :-)

**Comment by aroemers** [comment]
Hi @danielsz and @tolitius,

I agree that `mount` would be clearer than `state` in the namespace. However, when separating te two, how do we deal with common logic? For instance a function like [this](https://github.com/aroemers/system/blob/814897b49d1df90a63d991b805aa21b45423534f/src/system/components/elasticsearch.clj#L8-L12)? A structure like:

- `system.jetty` - common logic
- `system.jetty.component` - component logic, using common logic
- `system.jetty.mount` - mount logic, using common logic

But that would be breaking. Any ideas?

**Comment by danielsz** [comment]
Hi @aroemers, 

OK, we have a couple of options here.

1, The next release of `system` is breaking anyway, although not as radically as the whole namespace overhaul suggested by @aroemers. But if it found to be the best solution, it is doable.

2, It is possible to achieve almost the same without breaking everything with a different namespace scheme.

`system.common.jetty` instead of `system.jetty`  
`system.component.jetty` instead of `system.jetty.component`
`system.mount.jetty` instead of `system.jetty.mount`

**Comment by aroemers** [comment]
That second option sounds good to me, @danielsz. I'll work on it in the coming days.

**Comment by danielsz** [comment]
Fantastic, thank you @aroemers!

**Comment by aroemers** [comment]
Hi @danielsz, a short heads up: I am still working on this, one system after the other.

**Comment by danielsz** [comment]
@aroemers Thanks for the update and kudos to you!

**Comment by danielsz** [comment]
Separate branch available with mount support. Discussion here: #84
