### ISSUE TITLE
How to use mount with boot.system/system

### ISSUE THREAD

**Issue by arichiardi** [danielsz/system#81]
Hey Daniel, I tried to analyze `system.boot/system` for usage with `mount` but of course the whole `reloaded.repl` harness just does not fit the no-system-instance model of `mount`.

However, @tolitius created this little library for reifing a system in mount: https://github.com/tolitius/yurt.

Just putting this here in order to ponder. A user could create a `yurt` and pass it to `system`, another idea is to duplicate the whole task in another mount-only library. I still need to understand which approach is the best...

In any case, good job, good job, good job!

**Comment by danielsz** [comment]
Hi @arichiardi, 

Thank you for the kind words.

It sounds to me that it would be cleaner to have a different task altogether to manage `yurts`.

We have an ongoing discussion about how to bring `mount` to `system`, but it's been a while we haven't convened. 
@tolitius @aroemers

#73

**Comment by arichiardi** [comment]
I tried something without `yurt` and failed because a `system` is the requirement of not only the task but also the helper functions, so yes we would probably need a separate task to generate it.

**Comment by danielsz** [comment]
Your mount branch is ready to explore and refine, dear Andrea. :-)

I've pushed the excellent work of @aroemers as a separate development branch. 

Discussion is happening here: https://github.com/danielsz/system/pull/84

**Comment by arichiardi** [comment]
Thanks @danielsz for the mention, I'll have a look ASAP ;)

**Comment by arichiardi** [comment]
Magnificent work in the PR!
