### ISSUE TITLE
Consider a regex option for resets

### ISSUE THREAD

**Issue by flyingmachine** [danielsz/system#85]
Right now `system` uses `boot.core/by-name` with the `files` option in [`boot.clj`](https://github.com/danielsz/system/blob/master/src/system/boot.clj#L30). Consider adding a regex option that would use `boot.core/by-re`.

My use case is that I want all files within a directory to trigger a reset (I'm using weavejester's duct, and I want all endpoints to trigger a reset).

**Comment by danielsz** [comment]
Thank you @flyingmachine. Deployed in `0.3.1-SNAPSHOT`
