### ISSUE TITLE
Boot tasks/tooling without all the dependencies

### ISSUE THREAD

**Issue by martinklepsch** [danielsz/system#90]
Have you considered splitting this repo in two, one for the tooling aspects (boot/lein) and one for the a la carte components? I want to use the system tasks but having to add exclusions for every dependency is a bit of a pain. :)

**Comment by danielsz** [comment]
`system` has only 5 dependencies. They are trouble-free and almost ubiquitous.  Do you really add exclusions for them?  Which ones?

**Comment by martinklepsch** [comment]
Oh my. Forget what I said, I didn't see the `:dev` qualifier :facepalm:

Thanks for the quick reply!

**Comment by danielsz** [comment]
No problem, Martin. Enjoy!
