### ISSUE TITLE
Start idempotency

### ISSUE THREAD

**Issue by SevereOverfl0w** [danielsz/system#95]
Having a quick peruse through the components, and it seems that you have good `stop` idempotency.

To do `start` idempotency, components should check for their stateful part (server, connection, etc.) is already created in the `start` part of the protocol. https://github.com/stuartsierra/component#idempotence

```
  (start [this]
    (if connection  ; already started
      this
      (assoc this :connection (connect host port)))
```

**Comment by danielsz** [comment]
Good suggestion, @SevereOverfl0w. PR welcome.

**Comment by danielsz** [comment]
Feel free to reopen if there's something else to add.
